# Generated by Django 4.1.7 on 2023-08-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='opennames',
            name='idx_my_model_name1',
        ),
        migrations.AddIndex(
            model_name='opennames',
            index=models.Index(fields=['local_type'], name='idx_opennames_local_type'),
        ),
    ]
