# Generated by Django 4.1.7 on 2023-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0002_remove_opennames_idx_my_model_name1_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='opennames',
            index=models.Index(condition=models.Q(('local_type', 'Postcode')), fields=['name1'], name='postcode_geocoder'),
        ),
    ]
